require("lua.options")
require("lua.plugins")
require("lua.mappings")
require("lua.plugconf.lspconfig")
require("lua.plugconf.catpuccin")
require("lua.scripts.block_repeats")
require("lua.scripts.testmaker")
require("lua.scripts.b")
